name: create a release on merge

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: release-please-action
        uses: google-github-actions/release-please-action@v2.19.2
        with:
          token: ${{ secrets.TOKEN_REPO }}
          release-type: node
          default-branch: master
  merge:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Merge pull requests (automerge-action)
        # You may pin to the exact commit or the version.
        # uses: pascalgn/automerge-action@01fb84a9d077930bf9d16d1f7fa3fe2ffe45aabe
        uses: pascalgn/automerge-action@v0.14.2
        env:
          MERGE_LABELS: 'autorelease: pending'
          GITHUB_TOKEN: ${{ secrets.TOKEN_REPO }}
